openapi: "3.0.3"
info:
  title: "accessibility_reporting_tool API"
  description: "accessibility_reporting_tool API"
  version: "1.0.0"
servers:
- url: "https://accessibility_reporting_tool"
paths:
  /api/reports/list:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ReportWithUrl"
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: ""
                Example#3:
                  value: ""
  /api/reports/new:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Rapport"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: ""
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
  /api/teams:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/TeamSummary"
  /api/teams/{id}/reports:
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing or malformed id"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: ""
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ReportforTeam"
  /api/teams/new:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/NewTeam"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: ""
                Example#3:
                  value: ""
                Example#4:
                  value: ""
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /api/users/details:
    get:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: ""
                Example#2:
                  value: ""
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserDetails"
components:
  schemas:
    Function1:
      type: "object"
      properties: {}
    Function1_? super HTML:
      type: "object"
    ReportWithUrl:
      type: "object"
      properties:
        url:
          type: "string"
        navn:
          type: "string"
    Rapport:
      type: "object"
      properties:
        name:
          type: "string"
        urlTilSiden:
          type: "string"
        team:
          type: "string"
    TeamSummary:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
    ReportforTeam:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        url:
          type: "string"
    NewTeam:
      type: "object"
      properties:
        name:
          type: "string"
        email:
          type: "string"
        members:
          type: "array"
          items:
            type: "string"
    OrganizationUnit:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        email:
          type: "string"
        members:
          type: "array"
          items:
            type: "string"
    TestData:
      type: "object"
      properties:
        ident:
          type: "string"
        url:
          type: "string"
    Author:
      type: "object"
      properties:
        email:
          type: "string"
        oid:
          type: "string"
    SuccessCriterion:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        principle:
          type: "string"
        guideline:
          type: "string"
        tools:
          type: "string"
        number:
          type: "string"
        breakingTheLaw:
          type: "string"
        lawDoesNotApply:
          type: "string"
        tooHardToComply:
          type: "string"
        contentGroup:
          type: "string"
        status:
          type: "string"
          enum:
          - "COMPLIANT"
          - "NON_COMPLIANT"
          - "NOT_APPLICABLE"
          - "NOT_TESTED"
        wcagUrl:
          type: "string"
        helpUrl:
          type: "string"
        wcagVersion:
          type: "string"
        wcagLevel:
          type: "string"
          enum:
          - "A"
          - "AA"
          - "AAA"
          - "UNKNOWN"
        successCriterionNumber:
          type: "string"
    Report:
      type: "object"
      properties:
        reportId:
          type: "string"
        url:
          type: "string"
        descriptiveName:
          type: "string"
        organizationUnit:
          $ref: "#/components/schemas/OrganizationUnit"
        version:
          type: "string"
          enum:
          - "V1"
          - "V2"
        testData:
          $ref: "#/components/schemas/TestData"
        author:
          $ref: "#/components/schemas/Author"
        successCriteria:
          type: "array"
          items:
            $ref: "#/components/schemas/SuccessCriterion"
        filters:
          type: "array"
          items:
            type: "string"
        created:
          type: "string"
          format: "date-time"
        lastChanged:
          type: "string"
          format: "date-time"
        contributers:
          type: "array"
          items:
            $ref: "#/components/schemas/Author"
        lastUpdatedBy:
          $ref: "#/components/schemas/Author"
        reportType:
          type: "string"
          enum:
          - "AGGREGATED"
          - "SINGLE"
    UserDetails:
      type: "object"
      properties:
        email:
          type: "string"
        reports:
          type: "array"
          items:
            $ref: "#/components/schemas/Report"
        teams:
          type: "array"
          items:
            type: "string"