name: Gradle dependency check

on:
  workflow_dispatch

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run gradle dependency task
        run: ./gradlew dependencyUpdates
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Check pending updates
        run: python3  check_dependencies.py