name: Gradle dependency check

on:
  workflow_dispatch
permissions:
  contents: write

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Get current date
        id: date
        run: echo "$(date +'%Y-%m-%d')"
      - name: Check pending updates
        id: dependency-check
        run: |
          set +e
          git checkout -b "pending-updates-$(date -u +%Y-%m-%dT%H%M)"
          python3 check_dependencies.py --runTask
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          echo "branch=pending-updates-$(date -u +%Y-%m-%dT%H%M)"
      - name: Create PR
        if: ${{ steps.dependency-check.outputs.exitcode }} != '0'
        run: | 
          echo "Found ${{ steps.dependency-check.outputs.exitcode }} pending updates, creating PR"
          git config user.email "${{ github.run_id }}+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m 'Dependencies check failed $(date -u +%Y-%m-%dT%H%M)'
          git push --set-upstream origin -u ${{ steps.dependency-check.outputs.branch }}
          gh pr create --title "Dependency updates required" --body "See log in dependency_updates for details"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: No pending dependency updates
        if: ${{ steps.dependency-check.outputs.exitcode }} == '0'
        run: |
          echo "Gradle dependency scan at $(date -u +%Y-%m-%dT%H%M) completed without finding any outdated dependencies"